### ISSUE TITLE
Tap not detected

### ISSUE THREAD

**Issue by fabiosoft** [fahidattique55/FAPaginationLayout#1]
Tap is not detected on continuous scrolling of UICollectionView... but it's triggered as a scroll gesture and the next card is presented on screen.
I should wait a couple of seconds before the item could be selected

I even tried using a `UITapGestureRecognizer` instead `didSelectItemAt` on the cell view but it keeps scrolling

Idea for Solutions?

**Comment by fahidattique55** [comment]
Hi fabiosoft,

That is a good catch. I will resolve the issue soon. Thanks for letting me know.

Thanks & Regards

**Comment by fahidattique55** [comment]
Hi fabiosoft,

Did you test it with scroll de-accleration rate as fast?

**Comment by fabiosoft** [comment]
Sure! 
Anyway normal speed is very very slow...

**Comment by CavalcanteLeo** [comment]
Even the `didSelectItemAtIndexPath` is buggy

If the FAPaginationLayout is scrolling, and i click on the current showing cell, it goes to the next cell, and does not click on it.

Ps: `UIScrollViewDecelerationRateFast` is set

**Comment by hardik99** [comment]
I am facing the same issue. 

Can you plz help me if you have any solution?

**Comment by CavalcanteLeo** [comment]
I changed to https://github.com/WenchaoD/FSPagerView, also has another alternative https://github.com/KelvinJin/AnimatedCollectionViewLayout

**Comment by fahidattique55** [comment]
Issue is fixed in newer version v1.1.0
